GET http://localhost:9090/hello
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJodHRwOi8vMC4wLjAuMDo4MDgwL2hlbGxvIiwiaXNzIjoiaHR0cDovLzAuMC4wLjA6ODA4MC8iLCJleHAiOjE2NDI5NDc5MjksInVzZXJuYW1lIjoiZm9vIn0.lAsgLasRmDB5ZM8cKjdPN2RiaT9UgmTDK012rl2gPIk